scrape_configs:
  - job_name: 'gateway-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets:
        - gateway:8000
  - job_name: 'data-api-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets:
          - data-api-stable:8080
          - data-api:8081