spring:
  application:
    name: data-api
  profiles:
    active:
      - chaos-monkey
      - chaos-monkey-config
      - circuit-breaker
      - time-limiter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.szewczyk.mgr: DEBUG

management:
  endpoint:
    health:
      enabled: true
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8081