version: "3.5"

services:
  data-api-stable:
    build: ../data-api-stable/.
    image: "data-api-stable:latest"
    ports:
      - 8080
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
    networks:
      - data-api-network

  data-api:
    build: ../data-api/.
    image: "data-api:latest"
    ports:
      - 8081
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
    networks:
      - data-api-network

networks:
  data-api-network:
    external: true
    name: custom-network

# run with:
# docker-compose -f docker-compose-data-api.yml up --scale data-api-stable=5 --scale data-api=5 -d